### ISSUE TITLE
Get a new laptop

### ISSUE THREAD

**Issue by dmadisetti** [dmadisetti/.dots#334]
Some good motivation to actually finish my thesis and defend

Looking at the framework 13 with _nothing_

 - Optane inside: boot partition + cache
 - External modules:
   - 1 ssd just for `/nix/store`
   - 1 sd card reader ?? I like the idea of siloed user vs os space- maybe I get another ssd
   - 1 sd card drawer
   - 1 USB c
 
 - tmpfs impermanence #318 - loads of memory
 - Disko #134 

Edit:
---
"Mixed" mode might be possible with optane: http://web.archive.org/web/20240128020611/https://www.intel.com/content/www/us/en/developer/articles/guide/qsg-part2-linux-provisioning-with-optane-pmem.html could resize pmem to just boot image. I don't see anything in Nix Search, and Optane is technically deprecated, so likely a little bit of work. **edit edit**: also a little naive, I think it only supports specific hardware

But, could just use as nvme: Resource on using lvmcache with optane http://web.archive.org/web/20240417020616/https://codenotary.com/blog/ubuntu-how-to-use-intel-optane-memory-for-ssd-caching

Or since already a fan of ZFS, will probably start with L2ARC

**Comment by dmadisetti** [comment]
Help make this happen :wink: https://github.com/sponsors/dmadisetti

**Comment by adyotag** [comment]
Almost there! :-)

**Comment by dmadisetti** [comment]
You should still try snowflake out: https://snowflakeos.org/

**Comment by adyotag** [comment]
I'll put it on my Thinkpad after I back it up! :-)

**Comment by adyotag** [comment]
I think you should mark this as resolved.
